### ISSUE TITLE
How to run the project

### ISSUE THREAD

**Issue by Angerla** [mpecenin/wscad-2019#1]
I want to ask you about the structure of the project 's source code to help me solve some problem:
1.how can I run the  data providing 
2.how can I use my own data on your system 
3. the enviroment  to run project

**Comment by mpecenin** [comment]
The framework consists of the following structural model:
<img src="https://user-images.githubusercontent.com/9051921/104103155-4e205c80-527f-11eb-9dfe-ebac5835fbad.png" width="500">

I suggest you check one of the "HalideRL / run-xxx.sh" scripts. You can change according to your available hardware. You'll probably be more interested in the later sections of the script.

To test your own algorithm (image pipeline), as mentioned in the paper, you need to define the input pipeline and the scheduling options. I suggest checking the examples in the source code (grpc-halide / main.cpp), which extend from the `HalideBaseAlgorithm` class.

Also, to set up your RL environment, check the `ScheduleServiceImpl` class (grpc-halide / main.cpp) and the environment register (gym-halide / gym_halide / `__init__`.py).

**Comment by Angerla** [comment]
Hello, here are some problem confused :
1.I try to run the  "HalideRL / run-xxx.sh" scripts and it seems that I need to offer a parameter ("It mentioned as **Usage: ./run-cpu-node-6.sh HalideEnv**"). Is the parameter about the halide'source code  or the halide'environment or others?
2.I learnt the structural model you offered and  I just build the halide's environment. Is it  needed to build the OpenAL envoriment and gRPC environment ?

**Comment by mpecenin** [comment]
1. For example: HalideBlur-v3
2. No build required, as long as you have installed the python runtime,
grpc, etc.


Em seg., 11 de jan. de 2021 às 11:40, Junxiaoxiao <notifications@github.com>
escreveu:

**Comment by mpecenin** [comment]
1. For example: HalideBlur-v3 
2. No build required, as long as you have installed the runtimes, python, grpc, etc.

**Comment by Angerla** [comment]
**I run the ./run-cpu-node-6.sh HalideBlur-v3 facing some problem:**

>  grpc-halide: symbol lookup error: grpc-halide: undefined symbol: _ZN6Halide2_0E

**whether I have to compile the grpc-halide? And I try to compile the grpc-halide facing some new problem:**

>  In file included from schedule.grpc.pb.h:7,
                 from main.cpp:10:
schedule.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
   17 | #error This file was generated by an older version of protoc which is
      |  ^~~~~
schedule.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
   18 | #error incompatible with your Protocol Buffer headers.  Please
      |  ^~~~~
schedule.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
   19 | #error regenerate this file with a newer version of protoc.
      |  ^~~~~
In file included from schedule.grpc.pb.h:11,
                 from main.cpp:10:
/usr/local/include/grpc++/impl/codegen/method_handler_impl.h:26:10: fatal error: grpcpp/impl/codegen/method_handler_impl.h: No such file or directory
   26 | #include <grpcpp/impl/codegen/method_handler_impl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I want to ask you **what version grpc  and halide you used** ?

**Comment by mpecenin** [comment]
Please, check the paper for experimental setup.
- Linux x86_64
- GCC 5.4.0
- Python 3.4.8
- gRPC 1.12.0
- Halide 2018/02/15 (linux-64-gcc53-trunk)
- OpenAI Baselines 0.1.5
- OpenAI Gym 0.10.5

**Comment by Angerla** [comment]
Thank you. After I build the environment and I run **./run-cpu-node-6.sh HalideBlur-v3** facing a new problem: **"grpc:Error received from peer ipv4:127.0.0.1:50051"**. I want to ask you whether you know how to solve this(details):

>  Logging to ../result/ubuntu_HalideBlur-v3_2021-01-15-05-06-40-228551
2021-01-15 05:06:40.263122: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
random_seed: 2938590668
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Traceback (most recent call last):
  File "baselines/ppo1/run_halide.py", line 38, in <module>
    main()
  File "baselines/ppo1/run_halide.py", line 35, in main
    train(args.env, num_episodes=args.num_episodes, seed=args.seed)
  File "baselines/ppo1/run_halide.py", line 16, in train
    env = make_halide_env(env_id, seed)
  File "/home/zc/zc/Halid/wscad-2019-master/HalideRL/baselines/baselines/common/cmd_util.py", line 48, in make_halide_env
    env = gym.make(env_id)
  File "/home/zc/anaconda3/envs/zc/lib/python3.6/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/zc/anaconda3/envs/zc/lib/python3.6/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/zc/anaconda3/envs/zc/lib/python3.6/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/home/zc/zc/Halid/wscad-2019-master/HalideRL/gym-halide/gym_halide/envs/halide_env.py", line 28, in __init__
    response = self.stub.init(request)
  File "/home/zc/anaconda3/envs/zc/lib/python3.6/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/zc/anaconda3/envs/zc/lib/python3.6/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
**grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1610716000.336244739","description":"Error received from peer ipv4:127.0.0.1:50051","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"**
> ./run-cpu-node-6.sh: line 50: 73327 Aborted                 numactl --membind=0 --cpunodebind=0 grpc-halide "localhost:50051"  (wd: ~/zc/Halid/wscad-2019-master/HalideRL/grpc-halide)

**Comment by Angerla** [comment]
Thanks! I have the envoriment and I try to  **run the ./run-cpu-node-6.sh HalideBlur-v3** facing a **new problem**:

>  /home/zc/anaconda3/envs/zc/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  **result = entry_point.load(False)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc**
>   File "/home/zc/anaconda3/envs/zc/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with: status = StatusCode.UNAVAILABLE
details = "Socket closed"
debug_error_string = "{"created":"@1611029668.826363113","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_
line":1036,"grpc_message":"Socket closed","grpc_status":14}"

**And I want to ask you whether you know how to fix it ?**

**Comment by mpecenin** [comment]
Check your versions, grpc, python, etc. Probably you're trying to use different ones.

Or maybe rebuild the RPC calls (grpc-halide / schedule.proto.sh), but, if so, update python imports (gym-halide / gym_halide / envs / halide_env.py) and C++ includes (grpc-halide / main.cpp).

**Comment by Angerla** [comment]
Thanks! I check the versions and fix some of them. But I meet a new problem now:

>  **[xibeiidaxue-X299-WU8:23193] opal_os_dirpath_create: Error: Unable to create the sub-directory (/tmp/openmpi-sessions-trilinos@ascic142_0/1095) of (/tmp/openmpi-sessions-trilinos@ascic142_0/1095/0/0), mkdir failed [1]
[xibeiidaxue-X299-WU8:23193] [[48454,1],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 107
[xibeiidaxue-X299-WU8:23193] [[48454,1],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 402
[xibeiidaxue-X299-WU8:23193] [[48454,1],0] ORTE_ERROR_LOG: Error in file ess_hnp_module.c at line 638**

> **It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):
>  orte_session_dir failed
 --> Returned value Error (-1) instead of ORTE_SUCCESS**
**I want to ask you whether you have some suggestion?  Thanks again!!!**

**Comment by mpecenin** [comment]
Nothing specific, but I suggest exercising a little more with gRPC, parallel processing and interprocess communication in Python and C++.

**Comment by Angerla** [comment]
Thanks!!! 
But I think I may failed to rebuild the environment because this problem seems not been solved :

> **grpc : terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc**

**I want to ask you whether you can provide a download link for the virtual machine image or docker environment？I will be very grateful. Thanks again!!!**

**Comment by mpecenin** [comment]
No docker or vm was used, just host machine.

**Comment by Angerla** [comment]
I notice that the console output a var **random_seed** seems big. What is the random_seed' use?   Init for the data?

**Comment by mpecenin** [comment]
Sorry, with all due respect, but you really need a better foundation. I suggest further study and preliminary exercise on RL, OpenAI Gym, gRPC, etc.

**Comment by Angerla** [comment]
Thanks for your help these days.
